// <auto-generated />
using System;
using EntityDataModel.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EntityDataModel.Migrations
{
    [DbContext(typeof(EntityDataContext))]
    partial class EntityDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("SQL_Latin1_General_CP1_CI_AS")
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("EntityDataModel.Models.Category", b =>
            {
                b.Property<Guid>("CategoryId")
                    .HasColumnType("uniqueidentifier");

                b.Property<Guid?>("ParentId")
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("Title")
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.HasKey("CategoryId");

                b.ToTable("Category");
            });

            modelBuilder.Entity("EntityDataModel.Models.Comments", b =>
            {
                b.Property<Guid>("CommentId")
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("CommentMessage")
                    .HasColumnType("nvarchar(max)");

                b.Property<Guid?>("CreateBy")
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime?>("CreateTime")
                    .HasColumnType("datetime");

                b.Property<DateTime?>("LastEditTime")
                    .HasColumnType("datetime");

                b.HasKey("CommentId");

                b.HasIndex("CreateBy");

                b.ToTable("Comments");
            });

            modelBuilder.Entity("EntityDataModel.Models.Post", b =>
            {
                b.Property<Guid>("PostId")
                    .HasColumnType("uniqueidentifier");

                b.Property<Guid>("CategoryId")
                    .HasColumnType("uniqueidentifier");

                b.Property<Guid?>("CreateBy")
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime?>("CreateTime")
                    .HasColumnType("datetime");

                b.Property<Guid?>("LastEditBy")
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime?>("LastEditTime")
                    .HasColumnType("datetime");

                b.Property<string>("PostImageUrl")
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<string>("PostInfomation")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Title")
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<string>("Url")
                    .HasMaxLength(500)
                    .HasColumnType("nvarchar(500)")
                    .HasColumnName("URL");

                b.HasKey("PostId");

                b.ToTable("Post");
            });

            modelBuilder.Entity("EntityDataModel.Models.PostComment", b =>
            {
                b.Property<Guid>("PostId")
                    .HasColumnType("uniqueidentifier");

                b.Property<Guid>("CommentId")
                    .HasColumnType("uniqueidentifier");

                b.HasKey("PostId", "CommentId");

                b.HasIndex("CommentId");

                b.ToTable("Post_Comment");
            });

            modelBuilder.Entity("EntityDataModel.Models.PostTag", b =>
            {
                b.Property<Guid>("PostId")
                    .HasColumnType("uniqueidentifier");

                b.Property<Guid>("TagId")
                    .HasColumnType("uniqueidentifier");

                b.HasKey("PostId", "TagId");

                b.HasIndex("TagId");

                b.ToTable("Post_Tag");
            });

            modelBuilder.Entity("EntityDataModel.Models.Tag", b =>
            {
                b.Property<Guid>("TagId")
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("Title")
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.HasKey("TagId");

                b.ToTable("Tag");
            });

            modelBuilder.Entity("EntityDataModel.Models.User", b =>
            {
                b.Property<Guid>("UserId")
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("Email")
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)");

                b.Property<string>("ImageUrl")
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<string>("Password")
                    .HasMaxLength(256)
                    .HasColumnType("nvarchar(256)");

                b.Property<string>("Role")
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)");

                b.Property<string>("UserName")
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)");

                b.HasKey("UserId");

                b.ToTable("User");
            });

            modelBuilder.Entity("EntityDataModel.Models.Comments", b =>
            {
                b.HasOne("EntityDataModel.Models.User", "CreateByNavigation")
                    .WithMany("Comments")
                    .HasForeignKey("CreateBy")
                    .HasConstraintName("FK_Comments_User");

                b.Navigation("CreateByNavigation");
            });

            modelBuilder.Entity("EntityDataModel.Models.PostComment", b =>
            {
                b.HasOne("EntityDataModel.Models.Comments", "Comment")
                    .WithMany("PostComment")
                    .HasForeignKey("CommentId")
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .IsRequired()
                    .HasConstraintName("FK_Post_Comment_Comments1");

                b.HasOne("EntityDataModel.Models.Post", "Post")
                    .WithMany("PostComment")
                    .HasForeignKey("PostId")
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .IsRequired()
                    .HasConstraintName("FK_Post_Comment_Post2");

                b.Navigation("Comment");

                b.Navigation("Post");
            });

            modelBuilder.Entity("EntityDataModel.Models.PostTag", b =>
            {
                b.HasOne("EntityDataModel.Models.Post", "Post")
                    .WithMany("PostTag")
                    .HasForeignKey("PostId")
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .IsRequired()
                    .HasConstraintName("FK_Post_Tag_Post");

                b.HasOne("EntityDataModel.Models.Tag", "Tag")
                    .WithMany("PostTag")
                    .HasForeignKey("TagId")
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .IsRequired()
                    .HasConstraintName("FK_Post_Tag_Tag");

                b.Navigation("Post");

                b.Navigation("Tag");
            });

            modelBuilder.Entity("EntityDataModel.Models.Comments", b =>
            {
                b.Navigation("PostComment");
            });

            modelBuilder.Entity("EntityDataModel.Models.Post", b =>
            {
                b.Navigation("PostComment");

                b.Navigation("PostTag");
            });

            modelBuilder.Entity("EntityDataModel.Models.Tag", b =>
            {
                b.Navigation("PostTag");
            });

            modelBuilder.Entity("EntityDataModel.Models.User", b =>
            {
                b.Navigation("Comments");
            });
#pragma warning restore 612, 618
        }
    }
}
